
# PulseLine - Configuracion de la Aplicacion
spring.main.headless=false
# Puerto del servidor embebido
server.port=8081
# Nombre de la aplicacion
spring.application.name=PulseLine Call Center

# Configuracionn de la Base de Datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:pulselinedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 accesible en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA / Hibernate
# Fuerza que JPA cree las tablas ANTES de ejecutar data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.pulseline=DEBUG
logging.level.org.springframework.web=INFO
