-- ======================================================
-- PulseLine - Datos Iniciales de Prueba
-- Se ejecuta automáticamente al arrancar la aplicación
-- ======================================================

-- Campañas
INSERT INTO CAMPANIAS (ID_CAMPANIA, NOMBRE, TIPO, FECHA_INICIO, FECHA_FIN)
VALUES ('CAMP-001', 'Soporte Técnico Q2', 'SOPORTE_TECNICO', '2024-04-01', '2024-06-30');

INSERT INTO CAMPANIAS (ID_CAMPANIA, NOMBRE, TIPO, FECHA_INICIO, FECHA_FIN)
VALUES ('CAMP-002', 'Ventas Verano 2024', 'VENTAS', '2024-06-01', '2024-08-31');

INSERT INTO CAMPANIAS (ID_CAMPANIA, NOMBRE, TIPO, FECHA_INICIO, FECHA_FIN)
VALUES ('CAMP-003', 'Cobranzas Julio', 'COBRANZAS', '2024-07-01', '2024-07-31');

-- Agentes
INSERT INTO AGENTES (ID_AGENTE, NOMBRE_COMPLETO, NUMERO_EMPLEADO, EMAIL, NIVEL_EXPERIENCIA)
VALUES ('AGT-001', 'Carlos Martínez', 'EMP-0001', 'carlos.martinez@pulseline.com', 'SENIOR');

INSERT INTO AGENTES (ID_AGENTE, NOMBRE_COMPLETO, NUMERO_EMPLEADO, EMAIL, NIVEL_EXPERIENCIA)
VALUES ('AGT-002', 'Ana Rodríguez', 'EMP-0002', 'ana.rodriguez@pulseline.com', 'INTERMEDIO');

INSERT INTO AGENTES (ID_AGENTE, NOMBRE_COMPLETO, NUMERO_EMPLEADO, EMAIL, NIVEL_EXPERIENCIA)
VALUES ('AGT-003', 'Pedro Sánchez', 'EMP-0003', 'pedro.sanchez@pulseline.com', 'JUNIOR');

INSERT INTO AGENTES (ID_AGENTE, NOMBRE_COMPLETO, NUMERO_EMPLEADO, EMAIL, NIVEL_EXPERIENCIA)
VALUES ('AGT-004', 'María González', 'EMP-0004', 'maria.gonzalez@pulseline.com', 'SENIOR');

-- Llamadas
INSERT INTO LLAMADAS (NUMERO_LLAMADA, FECHA_HORA, DURACION_SEGUNDOS, ID_AGENTE, ID_CLIENTE, RESULTADO)
VALUES ('CALL-001', '2024-07-15 09:30:00', 245, 'AGT-001', 'CLI-101', 'RESUELTA');

INSERT INTO LLAMADAS (NUMERO_LLAMADA, FECHA_HORA, DURACION_SEGUNDOS, ID_AGENTE, ID_CLIENTE, RESULTADO)
VALUES ('CALL-002', '2024-07-15 10:15:00', 180, 'AGT-002', 'CLI-102', 'PENDIENTE');

INSERT INTO LLAMADAS (NUMERO_LLAMADA, FECHA_HORA, DURACION_SEGUNDOS, ID_AGENTE, ID_CLIENTE, RESULTADO)
VALUES ('CALL-003', '2024-07-15 11:00:00', 420, 'AGT-003', 'CLI-103', 'ESCALADA');

INSERT INTO LLAMADAS (NUMERO_LLAMADA, FECHA_HORA, DURACION_SEGUNDOS, ID_AGENTE, ID_CLIENTE, RESULTADO)
VALUES ('CALL-004', '2024-07-15 11:45:00', 310, 'AGT-001', 'CLI-104', 'RESUELTA');

INSERT INTO LLAMADAS (NUMERO_LLAMADA, FECHA_HORA, DURACION_SEGUNDOS, ID_AGENTE, ID_CLIENTE, RESULTADO)
VALUES ('CALL-005', '2024-07-15 14:00:00', 95, 'AGT-004', 'CLI-105', 'CANCELADA');
